name = "Multi TEOS"
description = "Loads generated Multi TEOS ViennaPS outputs."
script = "../TEOSTrenchDeposition/multiTEOS.py"
config = "../TEOSTrenchDeposition/multiTEOS_config.txt"
dimension = 3
runner = "sdk"
