name = "Single TEOS"
description = "Loads generated Single TEOS ViennaPS outputs."
script = "../TEOSTrenchDeposition/singleTEOS.py"
config = "../TEOSTrenchDeposition/singleTEOS_config.txt"
dimension = 3
runner = "sdk"
