name = "Single TEOS"
description = "Loads generated Single TEOS ViennaPS outputs."
script = "../../viennaps_examples/TEOSTrenchDeposition/singleTEOS.py"
config = "../../viennaps_examples/TEOSTrenchDeposition/singleTEOS_config.txt"
dimension = 3
outputs = "../../viewer_outputs/viennaps_examples/runs/singleTEOS/interface_*.vtp"
original_outputs = "original_mesh_volume.vtu"
