"""Interactive Streamlit/PyVista viewer for lsmesher outputs."""

from __future__ import annotations

import io
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, cast

import numpy as np
import plotly.graph_objects as go
import pyvista as pv
import streamlit as st
from streamlit.web.cli import main as streamlit_main

from lsmesher.cli import MesherOptions, detect_dimension
from lsmesher.geometry_types import Face
from lsmesher.pipeline_2d import build_2d_poly_geometry, read_2d_layers
from lsmesher.pipeline_3d import DEFAULT_TARGET_TOTAL_FACES, DecimationOptions3D
from lsmesher.polygon_io_2d import write_vtp as write_vtp_2d

VIEWABLE_EXTENSIONS = (".vtp", ".vtu", ".vtk", ".off")
PRESETS_DIR_ENV = "LSMESHER_VIEWER_PRESETS_DIR"
DEFAULT_MAX_WIREFRAME_EDGES = 50_000
OUTPUT_DIR_NAME = "viewer_outputs"


@dataclass(frozen=True)
class Preset:
    """Named preset that can be loaded from files or generated by a script."""

    name: str
    description: str
    dimension: int | None = None
    files: tuple[Path, ...] = ()
    script: Path | None = None
    config: Path | None = None
    directory: Path | None = None
    original_patterns: tuple[str, ...] = ()


@dataclass(frozen=True)
class ConfigEntry:
    """Editable key/value entry from a preset config file."""

    key: str
    value: str


@dataclass(frozen=True)
class MeshRenderOptions:
    """Display options for rendering a mesh file."""

    show_edges: bool
    color: str
    fill_surfaces: bool = True
    all_cell_edges: bool = False
    max_edges: int | None = None


@dataclass(frozen=True)
class PyVistaPngOptions:
    """Display options for server-side PyVista screenshots."""

    show_edges: bool
    color: str
    fill_surfaces: bool = True
    all_cell_edges: bool = False
    width: int = 1600
    height: int = 1000


@dataclass(frozen=True)
class ProcessedMeshOptions:
    """Options that affect processed mesh output."""

    epsilon: float
    output_format: str
    run_mesher: bool
    decimation: DecimationOptions3D = field(default_factory=DecimationOptions3D)
    mesher: MesherOptions = field(default_factory=MesherOptions)


def _slug(value: str) -> str:
    """Return a stable Streamlit widget key fragment."""
    return "".join(character if character.isalnum() else "_" for character in value)


def _discover_files(root: Path) -> list[Path]:
    """Return viewable mesh files under root, skipping hidden/tool directories."""
    skipped_parts = {".git", ".venv", ".opencode", "__pycache__"}
    files: list[Path] = []
    for extension in VIEWABLE_EXTENSIONS:
        for path in root.rglob(f"*{extension}"):
            if skipped_parts.intersection(path.parts):
                continue
            if path.suffix.lower() == ".vtp":
                try:
                    detect_dimension(str(path))
                except ValueError:
                    continue
            files.append(path)
    return sorted(files)


def _metadata_output_files(
    metadata: dict[str, Any], preset_dir: Path
) -> tuple[Path, ...]:
    """Return explicit output files declared in preset.toml."""
    outputs = metadata.get("outputs", ())
    if isinstance(outputs, str):
        outputs = (outputs,)

    files: list[Path] = []
    for output in outputs:
        pattern = Path(str(output))
        if not pattern.is_absolute():
            pattern = preset_dir / pattern
        pattern = pattern.resolve()
        files.extend(sorted(pattern.parent.glob(pattern.name)))
    return tuple(path for path in files if path.is_file())


def _preset_from_metadata(preset_dir: Path) -> Preset | None:
    """Return a runnable preset declared by preset.toml, if present."""
    metadata_path = preset_dir / "preset.toml"
    if not metadata_path.exists():
        return None

    with metadata_path.open("rb") as metadata_file:
        metadata = tomllib.load(metadata_file)

    script = preset_dir / str(metadata["script"]) if "script" in metadata else None
    config = preset_dir / str(metadata["config"]) if "config" in metadata else None
    original_patterns = metadata.get("original_outputs", ())
    if isinstance(original_patterns, str):
        original_patterns = (original_patterns,)
    return Preset(
        name=str(
            metadata.get(
                "name",
                preset_dir.name.replace("_", " ").replace("-", " ").title(),
            )
        ),
        description=str(metadata.get("description", f"Loads {preset_dir.name}.")),
        dimension=int(metadata["dimension"]),
        files=_metadata_output_files(metadata, preset_dir),
        script=script,
        config=config,
        directory=preset_dir,
        original_patterns=tuple(str(pattern) for pattern in original_patterns),
    )


def _discover_preset_outputs(
    root: Path,
    *,
    dimension: int,
    excluded_patterns: tuple[str, ...] = (),
) -> tuple[Path, ...]:
    """Return generated viewable files matching a preset dimension."""
    files: list[Path] = []
    for path in _discover_files(root):
        if any(path.match(Path(pattern).name) for pattern in excluded_patterns):
            continue
        if path.suffix.lower() != ".vtp":
            files.append(path)
            continue
        try:
            if detect_dimension(str(path)) == dimension:
                files.append(path)
        except ValueError:
            continue
    return tuple(files)


def _presets(root: Path) -> list[Preset]:
    """Return presets discovered from the viewer preset directory."""
    presets_dir = Path(os.environ.get(PRESETS_DIR_ENV, root / "viewer_presets"))
    if not presets_dir.exists():
        return []

    presets: list[Preset] = []
    for preset_dir in sorted(path for path in presets_dir.iterdir() if path.is_dir()):
        metadata_preset = _preset_from_metadata(preset_dir)
        if metadata_preset is not None:
            generated_outputs = _discover_preset_outputs(
                _preset_output_dir(root, metadata_preset.name) / "generated_preset",
                dimension=metadata_preset.dimension or 3,
                excluded_patterns=metadata_preset.original_patterns,
            )
            preset_outputs = generated_outputs or metadata_preset.files
            if preset_outputs:
                metadata_preset = Preset(
                    name=metadata_preset.name,
                    description=metadata_preset.description,
                    dimension=metadata_preset.dimension,
                    files=preset_outputs,
                    script=metadata_preset.script,
                    config=metadata_preset.config,
                    directory=metadata_preset.directory,
                    original_patterns=metadata_preset.original_patterns,
                )
            presets.append(metadata_preset)
    return presets


def _read_config_entries(config_path: Path) -> list[ConfigEntry]:
    """Read editable entries from a simple key=value config file."""
    entries: list[ConfigEntry] = []
    for line in config_path.read_text(encoding="utf-8").splitlines():
        value_part = line.split("#", 1)[0].strip()
        if "=" not in value_part:
            continue
        key, value = value_part.split("=", 1)
        entries.append(ConfigEntry(key=key.strip(), value=value.strip()))
    return entries


def _write_config_with_values(
    source_path: Path,
    output_path: Path,
    values: dict[str, str],
) -> None:
    """Write a config file with updated values while preserving comments."""
    lines: list[str] = []
    for line in source_path.read_text(encoding="utf-8").splitlines():
        content, separator, comment = line.partition("#")
        if "=" not in content:
            lines.append(line)
            continue

        key, _value = content.split("=", 1)
        stripped_key = key.strip()
        if stripped_key not in values:
            lines.append(line)
            continue

        updated = f"{key.rstrip()} = {values[stripped_key]}"
        if separator:
            updated = f"{updated}  #{comment}"
        lines.append(updated)

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _preset_dimension(files: tuple[Path, ...]) -> int | None:
    """Return the detected preset dimension, preferring 2D when mixed."""
    dimensions: set[int] = set()
    for path in files:
        try:
            dimensions.add(detect_dimension(str(path)))
        except ValueError:
            continue
    if 2 in dimensions:
        return 2
    if 3 in dimensions:
        return 3
    return None


def _load_preset(
    preset: Preset,
    root: Path,
    *,
    config_values: dict[str, str] | None = None,
    force_generate: bool = False,
    output_dir: Path | None = None,
) -> tuple[list[Path], str]:
    """Load fixture files or execute a preset script and return generated meshes."""
    if preset.files and not force_generate:
        files = [path for path in preset.files if path.exists()]
        if not files:
            message = f"No files found for preset: {preset.name}"
            raise FileNotFoundError(message)
        return files, "Loaded committed fixture files."

    if preset.script is None or preset.config is None or preset.dimension is None:
        message = f"Preset has no files or script: {preset.name}"
        raise ValueError(message)

    workdir = _prepare_output_dir(
        output_dir or Path(tempfile.mkdtemp(prefix="lsmesher-preset-"))
    )
    config_path = workdir / preset.config.name
    _write_config_with_values(preset.config, config_path, config_values or {})

    env = os.environ.copy()
    python_paths = [str(root / "src")]
    if preset.directory is not None:
        python_paths.append(str(preset.directory))
    if env.get("PYTHONPATH"):
        python_paths.append(env["PYTHONPATH"])
    env["PYTHONPATH"] = os.pathsep.join(python_paths)
    result = subprocess.run(
        [
            sys.executable,
            str(preset.script),
            "-D",
            str(preset.dimension),
            str(config_path),
        ],
        cwd=workdir,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        message = (
            f"Preset failed with exit code {result.returncode}\n\n"
            f"stdout:\n{result.stdout}\n\nstderr:\n{result.stderr}"
        )
        raise RuntimeError(message)

    files = list(
        _discover_preset_outputs(
            workdir,
            dimension=preset.dimension,
            excluded_patterns=preset.original_patterns,
        )
    )
    if not files:
        message = f"Preset ran successfully but produced no viewable files in {workdir}"
        raise FileNotFoundError(message)
    return files, f"Generated {len(files)} file(s) in {workdir}."


def _display_path(path: Path, root: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def _output_key(value: str) -> str:
    """Return a filesystem-safe output directory key."""
    key = "".join(character if character.isalnum() else "_" for character in value)
    return key.strip("_") or "preset"


def _preset_output_dir(root: Path, preset_name: str) -> Path:
    """Return the generated output directory for one preset."""
    return root / OUTPUT_DIR_NAME / _output_key(preset_name)


def _prepare_output_dir(path: Path) -> Path:
    """Create an empty output directory and return it."""
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True)
    return path


def _preset_original_mesh_files(
    preset: Preset,
    root: Path,
    raw_files: list[Path],
) -> list[Path]:
    """Return native ViennaPS meshes generated for a preset."""
    if not preset.original_patterns:
        return []
    directories = list(dict.fromkeys(path.parent for path in raw_files))
    directories.extend(
        (
            _preset_output_dir(root, preset.name) / "download_source",
            _preset_output_dir(root, preset.name) / "generated_preset",
        )
    )
    if preset.directory is not None:
        directories.append(preset.directory)

    for directory in directories:
        if not directory.exists():
            continue
        files: set[Path] = set()
        for pattern in preset.original_patterns:
            files.update(
                path for path in directory.glob(Path(pattern).name) if path.is_file()
            )
        if files:
            return sorted(files)
    return []


def _processed_output_files(output_path: Path) -> list[Path]:
    """Return mesh data and mesher sidecars belonging to processed output."""
    data_suffixes = {
        ".edge",
        ".ele",
        ".face",
        ".log",
        ".node",
        ".off",
        ".poly",
        ".vtk",
        ".vtp",
        ".vtu",
        ".json",
    }
    return sorted(
        path
        for path in output_path.parent.iterdir()
        if path.is_file() and path.suffix.lower() in data_suffixes
    )


# Mesh suffixes ParaView can open directly (sidecars like .log/.poly are skipped).
_PARAVIEW_READABLE_SUFFIXES = frozenset(
    {".vtp", ".vtu", ".vts", ".vtr", ".vti", ".vtk", ".pvd", ".stl", ".obj"}
)

# ParaView treats a ``.py`` handed to "Load State" (or ``--state``) as a state
# file, so this script loads through the same menu as a ``.pvsm`` would. Unlike a
# ``.pvsm``, it resolves paths at run time relative to its own location, so the
# archive stays portable no matter where it is extracted.
PARAVIEW_STATE_FILE_NAME = "open_in_paraview.py"

# Short labels for each archive category, used in ParaView pipeline names.
_CATEGORY_LABELS = {
    "meshed_output": "mesh",
    "raw_files": "raw",
    "original_mesh": "original",
}

# Level-set interface files are named ``interface_<layer>`` by ViennaPS.
_INTERFACE_LAYER_RE = re.compile(r"interface[_-]?(\d+)", re.IGNORECASE)


def _paraview_source_label(preset_name: str, arcname: str) -> str:
    """Return an informative ParaView pipeline name for one archive entry.

    Every name carries the preset; level-set interfaces also carry their layer.
    """
    parts = Path(arcname).parts
    category = _CATEGORY_LABELS.get(parts[0], parts[0]) if parts else ""
    stem = Path(arcname).stem
    layer = _INTERFACE_LAYER_RE.search(stem)
    detail = f"level set layer {int(layer.group(1))}" if layer else stem
    return f"{preset_name} - {category} - {detail}"


def _paraview_state_script(preset_name: str, arcnames: list[str]) -> str | None:
    """Build a ParaView state script loading every readable arcname into one view.

    Returns ``None`` when no archive entry is a ParaView-readable mesh.
    """
    meshes = [
        (arcname, _paraview_source_label(preset_name, arcname))
        for arcname in arcnames
        if Path(arcname).suffix.lower() in _PARAVIEW_READABLE_SUFFIXES
    ]
    if not meshes:
        return None

    listing = "\n".join(f"    ({arcname!r}, {label!r})," for arcname, label in meshes)
    return f'''"""Open every mesh from preset {preset_name!r} in ParaView.

Load it with File > Load State and pick this file, or run
``paraview --state={PARAVIEW_STATE_FILE_NAME}`` or ``pvpython {PARAVIEW_STATE_FILE_NAME}``.
Data paths resolve relative to this script, so it works wherever the archive is
extracted.
"""
import os

from paraview import servermanager
from paraview.simple import (
    ColorBy,
    GetActiveViewOrCreate,
    GetColorTransferFunction,
    OpenDataFile,
    RenameSource,
    Render,
    ResetCamera,
    Show,
)

# (path relative to this script, ParaView pipeline name)
_MESHES = [
{listing}
]

# Cell array holding material ids in ViennaPS/lsmesher volume meshes.
_MATERIAL_ARRAY = "Material"

# White for mesh edges.
_EDGE_COLOR = [1.0, 1.0, 1.0]

# High-contrast qualitative palette (teal/cyan omitted so material fills never
# blend into the teal edges). Cycled across the material ids actually present.
_MATERIAL_PALETTE = [
    [0.84, 0.15, 0.16],
    [0.12, 0.47, 0.71],
    [1.00, 0.60, 0.00],
    [0.17, 0.63, 0.17],
    [0.58, 0.40, 0.74],
    [0.55, 0.34, 0.29],
    [0.89, 0.47, 0.76],
    [0.74, 0.74, 0.13],
    [0.09, 0.24, 0.55],
    [0.65, 0.00, 0.13],
    [0.45, 0.24, 0.64],
    [0.95, 0.80, 0.20],
]


def _base_dirs():
    dirs = []
    try:
        dirs.append(os.path.dirname(os.path.abspath(__file__)))
    except NameError:
        pass
    dirs.append(os.getcwd())
    return dirs


def _resolve(relative_path):
    for base in _base_dirs():
        candidate = os.path.join(base, relative_path)
        if os.path.exists(candidate):
            return candidate
    return None


def _material_values(source):
    """Return the sorted distinct material ids in a source (numpy not required)."""
    values = set()
    stack = [servermanager.Fetch(source)]
    while stack:
        data = stack.pop()
        if data is None:
            continue
        get_cell_data = getattr(data, "GetCellData", None)
        if get_cell_data is not None and get_cell_data() is not None:
            array = get_cell_data().GetArray(_MATERIAL_ARRAY)
            if array is not None:
                for i in range(array.GetNumberOfTuples()):
                    values.add(array.GetComponent(i, 0))
        new_iterator = getattr(data, "NewIterator", None)
        if new_iterator is not None:
            iterator = new_iterator()
            iterator.InitTraversal()
            while not iterator.IsDoneWithTraversal():
                stack.append(iterator.GetCurrentDataObject())
                iterator.GoToNextItem()
    return sorted(values)


def _format_value(value):
    return str(int(value)) if float(value).is_integer() else repr(value)


def _color_materials_by_category(material_sources):
    """Give each distinct material id a distinct high-contrast color."""
    values = set()
    for source in material_sources:
        values.update(_material_values(source))
    if not values:
        return
    annotations = []
    colors = []
    for index, value in enumerate(sorted(values)):
        text = _format_value(value)
        annotations.append(text)
        annotations.append(text)
        colors.extend(_MATERIAL_PALETTE[index % len(_MATERIAL_PALETTE)])
    lut = GetColorTransferFunction(_MATERIAL_ARRAY)
    lut.InterpretValuesAsCategories = 1
    lut.AnnotationsInitialized = 1
    lut.Annotations = annotations
    lut.IndexedColors = colors


def load_preset_data():
    view = GetActiveViewOrCreate("RenderView")
    material_sources = []
    for relative_path, name in _MESHES:
        path = _resolve(relative_path)
        if path is None:
            print("Skipped (not found next to this script):", relative_path)
            continue
        source = OpenDataFile(path)
        if source is None:
            continue
        RenameSource(name, source)
        representation = Show(source, view)
        representation.Representation = "Surface With Edges"
        representation.EdgeColor = _EDGE_COLOR
        if _MATERIAL_ARRAY in source.CellData.keys():
            ColorBy(representation, ("CELLS", _MATERIAL_ARRAY))
            material_sources.append(source)
    _color_materials_by_category(material_sources)
    ResetCamera(view)
    Render()


load_preset_data()
'''


def _preset_data_zip(
    preset_name: str,
    *,
    processed_files: list[Path],
    raw_files: list[Path],
    original_files: list[Path],
) -> bytes:
    """Build a ZIP containing processed, raw, and native ViennaPS meshes."""
    if not processed_files or not raw_files or not original_files:
        message = "Preset ZIP requires processed, raw, and original mesh files."
        raise ValueError(message)

    entries: list[tuple[str, Path]] = []
    for directory, files in (
        ("meshed_output", processed_files),
        ("raw_files", raw_files),
        ("original_mesh", original_files),
    ):
        used_names: set[str] = set()
        for path in files:
            name = path.name
            if name in used_names:
                name = f"{path.parent.name}_{name}"
            used_names.add(name)
            entries.append((f"{directory}/{name}", path))

    state_script = _paraview_state_script(
        preset_name, [arcname for arcname, _ in entries]
    )

    archive_buffer = io.BytesIO()
    with zipfile.ZipFile(
        archive_buffer,
        mode="w",
        compression=zipfile.ZIP_DEFLATED,
    ) as archive:
        readme = (
            f"Preset: {preset_name}\n\n"
            "meshed_output/: lsmesher processed mesh and mesher sidecars\n"
            "raw_files/: per-interface ViennaPS files supplied to lsmesher\n"
            "original_mesh/: native combined ViennaPS output\n"
        )
        if state_script is not None:
            readme += (
                f"\n{PARAVIEW_STATE_FILE_NAME}: ParaView state that opens every mesh "
                "above at once. Extract this ZIP, then in ParaView use File > Load "
                f"State and pick {PARAVIEW_STATE_FILE_NAME} (ParaView loads .py "
                "state files). Data paths resolve relative to the script, so it "
                "works from any extraction folder.\n"
            )
        archive.writestr("README.txt", readme)
        for arcname, path in entries:
            archive.write(path, arcname=arcname)
        if state_script is not None:
            archive.writestr(PARAVIEW_STATE_FILE_NAME, state_script)
    return archive_buffer.getvalue()


def _line_coordinates(mesh: pv.DataSet) -> tuple[list[float], list[float], list[float]]:
    """Return Plotly line coordinates separated by None values."""
    if not isinstance(mesh, pv.PolyData) or mesh.lines.size == 0:
        return [], [], []

    points = np.asarray(mesh.points)
    x_coords: list[float] = []
    y_coords: list[float] = []
    z_coords: list[float] = []
    offset = 0
    while offset < mesh.lines.size:
        count = int(mesh.lines[offset])
        indices = mesh.lines[offset + 1 : offset + 1 + count]
        for index in indices:
            point = points[int(index)]
            x_coords.append(float(point[0]))
            y_coords.append(float(point[1]))
            z_coords.append(float(point[2]))
        x_coords.append(None)  # type: ignore[arg-type]
        y_coords.append(None)  # type: ignore[arg-type]
        z_coords.append(None)  # type: ignore[arg-type]
        offset += count + 1
    return x_coords, y_coords, z_coords


def _surface_triangles(mesh: pv.DataSet) -> tuple[np.ndarray, np.ndarray] | None:
    """Return points and triangle indices for Plotly Mesh3d."""
    surface = mesh.extract_surface(algorithm="dataset_surface").triangulate()
    if not isinstance(surface, pv.PolyData) or surface.faces.size == 0:
        return None

    faces = surface.faces.reshape((-1, 4))
    if faces.size == 0:
        return None
    return np.asarray(surface.points), faces[:, 1:4]


def _mesh_edge_coordinates(
    mesh: pv.DataSet,
    *,
    all_cell_edges: bool,
    max_edges: int | None = None,
) -> tuple[list[float], list[float], list[float]]:
    """Return edge line coordinates for either all cells or the extracted surface."""
    if not all_cell_edges:
        return _line_coordinates(mesh.extract_surface(algorithm="dataset_surface"))

    points = np.asarray(mesh.points)
    edges: set[tuple[int, int]] = set()
    for cell_id in range(mesh.n_cells):
        point_ids = list(mesh.get_cell(cell_id).point_ids)
        if len(point_ids) < 2:
            continue
        for index, start in enumerate(point_ids):
            end = point_ids[(index + 1) % len(point_ids)]
            edges.add((min(start, end), max(start, end)))

    edge_list = sorted(edges)
    if max_edges is not None:
        edge_list = edge_list[:max_edges]

    x_coords: list[float] = []
    y_coords: list[float] = []
    z_coords: list[float] = []
    for start, end in edge_list:
        for point_id in (start, end):
            point = points[point_id]
            x_coords.append(float(point[0]))
            y_coords.append(float(point[1]))
            z_coords.append(float(point[2]))
        x_coords.append(None)  # type: ignore[arg-type]
        y_coords.append(None)  # type: ignore[arg-type]
        z_coords.append(None)  # type: ignore[arg-type]
    return x_coords, y_coords, z_coords


def _padded_range(
    lower: float, upper: float, *, pad_fraction: float = 0.12
) -> list[float]:
    """Return a Plotly axis range with enough padding for first-load framing."""
    span = upper - lower
    pad = max(abs(lower), 1.0) * pad_fraction if span == 0 else span * pad_fraction
    return [lower - pad, upper + pad]


def _render_mesh(
    path: Path,
    *,
    options: MeshRenderOptions,
) -> None:
    mesh = cast("pv.DataSet", pv.read(path))
    traces: list[Any] = []

    triangles = _surface_triangles(mesh) if options.fill_surfaces else None
    if options.fill_surfaces and triangles is not None:
        points, faces = triangles
        traces.append(
            go.Mesh3d(
                x=points[:, 0],
                y=points[:, 1],
                z=points[:, 2],
                i=faces[:, 0],
                j=faces[:, 1],
                k=faces[:, 2],
                color=options.color,
                opacity=0.85,
                name=path.name,
                showscale=False,
            )
        )

    if options.show_edges:
        x_coords, y_coords, z_coords = _mesh_edge_coordinates(
            mesh,
            all_cell_edges=options.all_cell_edges,
            max_edges=options.max_edges,
        )
        if x_coords:
            rendered_edges = x_coords.count(None)
            traces.append(
                go.Scatter3d(
                    x=x_coords,
                    y=y_coords,
                    z=z_coords,
                    mode="lines",
                    line={"color": "#f8fafc", "width": 3},
                    name="edges",
                )
            )
            if (
                options.all_cell_edges
                and options.max_edges is not None
                and rendered_edges >= options.max_edges
            ):
                st.warning(
                    f"Wireframe display capped at {options.max_edges:,} edges to keep the viewer responsive."
                )

    if not traces:
        points = np.asarray(mesh.points)
        traces.append(
            go.Scatter3d(
                x=points[:, 0],
                y=points[:, 1],
                z=points[:, 2],
                mode="markers",
                marker={"color": options.color, "size": 3},
                name=path.name,
            )
        )

    bounds = mesh.bounds
    figure = go.Figure(data=traces)
    figure.update_layout(
        height=700,
        margin={"l": 0, "r": 0, "t": 0, "b": 0},
        paper_bgcolor="#0e1117",
        scene={
            "xaxis": {
                "title": "X",
                "backgroundcolor": "#0e1117",
                "range": _padded_range(bounds[0], bounds[1]),
            },
            "yaxis": {
                "title": "Y",
                "backgroundcolor": "#0e1117",
                "range": _padded_range(bounds[2], bounds[3]),
            },
            "zaxis": {
                "title": "Z",
                "backgroundcolor": "#0e1117",
                "range": _padded_range(bounds[4], bounds[5]),
            },
            "aspectmode": "data",
            "camera": {
                "eye": {"x": 0.0, "y": 0.0, "z": 3.0},
                "up": {"x": 0.0, "y": 1.0, "z": 0.0},
            },
        },
    )
    chart_key = f"plotly-{path}-{path.stat().st_mtime_ns}"
    st.plotly_chart(figure, width="stretch", key=chart_key)


def _pyvista_screenshot(path: Path, *, options: PyVistaPngOptions) -> Path:
    """Render a mesh to a PNG with PyVista offscreen rendering."""
    mesh = cast("pv.DataSet", pv.read(path))
    output_path = Path(tempfile.mkdtemp(prefix="lsmesher-pyvista-png-")) / "preview.png"
    plotter = pv.Plotter(
        off_screen=True,
        window_size=(options.width, options.height),
    )
    plotter.set_background("#0e1117")

    if options.all_cell_edges:
        plotter.add_mesh(
            mesh.extract_all_edges(),
            color="#f8fafc",
            line_width=1,
        )
    else:
        scalars = "Material" if "Material" in mesh.cell_data else None
        if options.fill_surfaces:
            plotter.add_mesh(
                mesh,
                scalars=scalars,
                cmap="tab20",
                color=None if scalars else options.color,
                show_edges=options.show_edges,
                edge_color="#f8fafc",
                line_width=1,
            )
        else:
            edge_mesh = mesh.extract_all_edges() if options.show_edges else mesh
            plotter.add_mesh(
                edge_mesh,
                color=options.color,
                line_width=1,
            )

    _set_png_camera(plotter, mesh)
    plotter.camera.parallel_projection = True
    plotter.reset_camera()
    plotter.screenshot(output_path)
    plotter.close()
    return output_path


def _set_png_camera(plotter: pv.Plotter, mesh: pv.DataSet) -> None:
    """Use a top-down 2D view, but keep Z vertical for spatial 3D meshes."""
    bounds = mesh.bounds
    if bounds[5] > bounds[4]:
        plotter.view_vector((1.0, 1.0, 0.6), viewup=(0.0, 0.0, 1.0))
    else:
        plotter.view_xy()


def _render_mesh_png(path: Path, *, options: PyVistaPngOptions) -> None:
    """Render a mesh to a PNG and display it in Streamlit."""
    image_path = _pyvista_screenshot(path, options=options)
    st.image(str(image_path), width="stretch")


def _write_uploaded_files(uploaded_files: list, directory: Path) -> list[Path]:
    paths: list[Path] = []
    for uploaded_file in uploaded_files:
        path = directory / uploaded_file.name
        path.write_bytes(uploaded_file.getbuffer())
        paths.append(path)
    return paths


def _decimation_cli_flags(decimation: DecimationOptions3D) -> list[str]:
    """Translate decimation options into `lsmesher mesh` CLI flags."""
    if not decimation.enabled:
        return ["--no-decimate"]
    flags = [
        "--decimate-quality",
        str(decimation.quality_threshold),
        "--decimate-boundary-weight",
        str(decimation.boundary_weight),
        "--decimate-planar-weight",
        str(decimation.planar_weight),
    ]
    if decimation.target_edge_length is not None:
        flags.extend(
            ("--decimate-target-edge-length", str(decimation.target_edge_length))
        )
    elif decimation.target_faces is not None:
        flags.extend(("--decimate-target-faces", str(decimation.target_faces)))
    else:
        flags.extend(
            (
                "--decimate-target-total-faces",
                str(decimation.target_total_faces or DEFAULT_TARGET_TOTAL_FACES),
            )
        )
    if decimation.optimal_placement:
        flags.append("--decimate-optimal-placement")
    flags.append(
        "--decimate-preserve-boundary"
        if decimation.preserve_boundary
        else "--no-decimate-preserve-boundary"
    )
    flags.append(
        "--decimate-planar-quadric"
        if decimation.planar_quadric
        else "--no-decimate-planar-quadric"
    )
    return flags


def _mesher_cli_flags(options: MesherOptions) -> list[str]:
    """Translate mesher quality options into `lsmesher mesh` CLI flags."""
    flags = [
        "--triangle-min-angle",
        str(options.triangle_min_angle),
        "--tetgen-quality-ratio",
        str(options.tetgen_quality_ratio),
        "--tetgen-min-dihedral",
        str(options.tetgen_min_dihedral),
        "--bottom-margin",
        str(options.bottom_margin),
        "--seam-protection-rings",
        str(options.seam_protection_rings),
    ]
    if options.tetgen_max_volume is not None:
        flags.extend(("--tetgen-max-volume", str(options.tetgen_max_volume)))
    return flags


def _run_pipeline(  # noqa: PLR0913
    input_paths: list[Path],
    *,
    epsilon: float,
    output_format: str,
    run_mesher: bool,
    output_path: Path | None = None,
    decimation: DecimationOptions3D | None = None,
    mesher: MesherOptions | None = None,
) -> Path:
    """Run the meshing pipeline in a subprocess and return the output path.

    The pipeline runs via ``lsmesher mesh`` in a child process on purpose:
    pymeshlab's bundled Qt runtime binds thread-local state to whichever
    thread first loads it, and Streamlit script threads are short-lived, so
    running it in the viewer process corrupts the heap and eventually aborts
    the whole viewer (glibc "corrupted size vs. prev_size" /
    "malloc_consolidate" errors). A subprocess also turns any native crash
    into a readable error instead of killing the viewer.
    """
    suffix = f".{output_format}"
    output_path = (
        output_path
        or Path(tempfile.mkdtemp(prefix="lsmesher-viewer-")) / f"mesh{suffix}"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)

    command = [
        sys.executable,
        "-m",
        "lsmesher.cli",
        "mesh",
        *[str(path) for path in input_paths],
        "--epsilon",
        str(epsilon),
        "--format",
        output_format,
        "--out",
        str(output_path),
        *([] if run_mesher else ["--no-mesh"]),
        *_mesher_cli_flags(mesher or MesherOptions()),
        *_decimation_cli_flags(decimation or DecimationOptions3D()),
    ]
    result = subprocess.run(command, capture_output=True, text=True, check=False)
    if result.stdout:
        sys.stdout.write(result.stdout)
    if result.returncode != 0:
        message = "\n\n".join(
            part
            for part in (
                f"Meshing pipeline failed with exit code {result.returncode}.",
                f"stdout:\n{result.stdout}" if result.stdout else "",
                f"stderr:\n{result.stderr}" if result.stderr else "",
            )
            if part
        )
        raise RuntimeError(message)

    return output_path


def _run_2d_polygon_preview(
    input_paths: list[Path],
    *,
    epsilon: float,
    output_path: Path | None = None,
) -> Path:
    """Write the pre-mesh 2D pipeline polygon to a temporary VTP file."""
    dimension = detect_dimension(str(input_paths[0]))
    if dimension != 2:
        message = "Pipeline polygon preview is only available for 2D VTP inputs."
        raise ValueError(message)

    geometry = build_2d_poly_geometry(
        read_2d_layers(input_paths),
        epsilon=epsilon,
        detect_holes=False,
    )
    output_path = (
        output_path
        or Path(tempfile.mkdtemp(prefix="lsmesher-polygon-")) / "polygon.vtp"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    write_vtp_2d(
        output_path,
        geometry.points,
        [Face(edge.as_tuple()) for edge in geometry.edges],
    )
    return output_path


def _write_2d_polygon_preview_output(
    input_paths: list[Path],
    *,
    epsilon: float,
    output_dir: Path,
) -> Path:
    """Write build_2d_poly_geometry output to a reachable output directory."""
    output_path = _prepare_output_dir(output_dir) / "polygon.vtp"
    return _run_2d_polygon_preview(
        input_paths,
        epsilon=epsilon,
        output_path=output_path,
    )


def _write_processed_mesh_output(
    input_paths: list[Path],
    *,
    options: ProcessedMeshOptions,
    output_dir: Path,
) -> Path:
    """Write processed mesh output to a reachable output directory."""
    output_dir = _prepare_output_dir(output_dir)
    output_path = output_dir / f"mesh.{options.output_format}"
    return _run_pipeline(
        input_paths,
        epsilon=options.epsilon,
        output_format=options.output_format,
        run_mesher=options.run_mesher,
        output_path=output_path,
        decimation=options.decimation,
        mesher=options.mesher,
    )


def _processed_mesh_retry_options(
    input_paths: list[Path],
    options: ProcessedMeshOptions,
) -> list[tuple[str, ProcessedMeshOptions, str | None]]:
    """Return processed mesh attempts and visible retry reasons."""
    attempts = [("selected settings", options, None)]
    if not input_paths:
        return attempts
    try:
        is_3d = detect_dimension(str(input_paths[0])) == 3
    except ValueError:
        is_3d = False
    if is_3d and options.run_mesher:
        retry_reason = (
            "TetGen can be sensitive to small geometry changes. Retrying with "
            "the same settings regenerates the preset and mesh without changing "
            "your decimation controls."
        )
        attempts.extend(
            (
                f"same settings retry {retry_index}",
                options,
                retry_reason,
            )
            for retry_index in range(1, 3)
        )
    return attempts


def _processed_mesh_failure_guidance(options: ProcessedMeshOptions) -> str:
    """Return actionable guidance after all processed mesh attempts fail."""
    if options.decimation.enabled:
        return (
            "All attempts failed with the selected settings. Try reducing "
            "decimation manually: increase the total face budget or reduce the "
            "target edge length, raise the "
            "quality threshold, or turn off optimal vertex placement."
        )
    return (
        "All attempts failed with decimation disabled. The generated surfaces may "
        "contain self-intersections; try changing the preset config or inspect the "
        "generated files."
    )


def _exception_summary(exc: Exception) -> str:
    """Return a compact single-line exception summary for retry messages."""
    message = str(exc).strip().splitlines()[0] if str(exc).strip() else repr(exc)
    return message[:240]


def _processed_tetgen_log_path(output_path: Path) -> Path:
    """Return the TetGen log next to a processed mesh output.

    TetGen outputs (``mesh.1.vtu``) and the POLY sidecar (``mesh.poly``)
    share the part of the name before the first dot, and the CLI writes the
    log as ``mesh.tetgen.log`` next to the POLY.
    """
    stem = output_path.name.split(".")[0]
    return output_path.with_name(f"{stem}.tetgen.log")


def _show_tetgen_log(output_path: Path) -> None:
    """Display the TetGen output for a processed mesh, when one exists."""
    log_path = _processed_tetgen_log_path(output_path)
    if not log_path.exists():
        return
    with st.expander("TetGen output", expanded=True):
        st.code(log_path.read_text(encoding="utf-8"), language=None)


def _show_decimation_report(output_path: Path) -> None:
    report_path = output_path.with_name(f"{output_path.stem}.decimation.json")
    if not report_path.exists():
        return
    report = json.loads(report_path.read_text(encoding="utf-8"))
    st.caption(
        "Decimation: "
        f"{report['original_faces']:,} → {report['achieved_faces']:,} unique faces "
        f"({report['mode']}, requested {report['requested_faces']:,}; "
        f"protected {report['protected_faces']:,}; "
        f"above target for safety {report['boundary_limited_faces']:,})."
    )


def _show_preset_data_download(
    preset: Preset,
    root: Path,
    *,
    output_path: Path,
    raw_files: list[Path],
    config_values: dict[str, str],
) -> None:
    """Render a complete preset ZIP download, generating native output if needed."""
    original_files = _preset_original_mesh_files(preset, root, raw_files)
    if not original_files:
        if preset.script is None or preset.config is None or preset.dimension is None:
            st.error("This preset has no generator configured for its original mesh.")
            return
        st.info(
            "This cached preset predates native ViennaPS mesh export. Click below to "
            "generate the original mesh and prepare the complete ZIP download."
        )
        if not st.button("Prepare preset data for download"):
            return
        with st.spinner(f"Generating native ViennaPS output for {preset.name}..."):
            _load_preset(
                preset,
                root,
                config_values=config_values,
                force_generate=True,
                output_dir=_preset_output_dir(root, preset.name) / "download_source",
            )
        original_files = _preset_original_mesh_files(preset, root, raw_files)
        if not original_files:
            st.error("Mesh generation did not produce the expected original files.")
            return

    archive = _preset_data_zip(
        preset.name,
        processed_files=_processed_output_files(output_path),
        raw_files=raw_files,
        original_files=original_files,
    )
    st.download_button(
        "Download preset data (.zip)",
        data=archive,
        file_name=f"{_output_key(preset.name)}.zip",
        mime="application/zip",
        help=(
            "Includes meshed_output, raw_files, the native ViennaPS original_mesh, "
            "and a ParaView state script (open_in_paraview.py) that opens every "
            "mesh at once via File > Load State."
        ),
    )


def _geometry_bounding_box_volume(input_paths: list[Path]) -> float:
    """Return the combined 3D bounding-box volume, or one when unavailable."""
    if not input_paths:
        return 1.0
    try:
        bounds = [pv.read(path).bounds for path in input_paths]
    except Exception:  # noqa: BLE001 - a bad preview path should not break controls.
        return 1.0
    spans = (
        max(bound[1] for bound in bounds) - min(bound[0] for bound in bounds),
        max(bound[3] for bound in bounds) - min(bound[2] for bound in bounds),
        max(bound[5] for bound in bounds) - min(bound[4] for bound in bounds),
    )
    volume = spans[0] * spans[1] * spans[2]
    return float(volume) if volume > 0 else 1.0


def _tetgen_volume_slider_options(input_paths: list[Path]) -> tuple[float, ...]:
    """Return logarithmic TetGen volume bounds scaled to the input geometry."""
    bounding_volume = _geometry_bounding_box_volume(input_paths)
    fractions = (
        1e-6,
        3e-6,
        1e-5,
        3e-5,
        1e-4,
        3e-4,
        1e-3,
        3e-3,
        1e-2,
        3e-2,
        1e-1,
    )
    return (0.0, *(bounding_volume * fraction for fraction in fractions))


def _format_volume_slider_value(value: float) -> str:
    """Format a TetGen volume bound for the Streamlit slider."""
    return "No limit" if value == 0 else f"{value:.3g}"


def _mesher_quality_sidebar_controls(
    dimension: int,
    defaults: MesherOptions,
    input_paths: list[Path],
) -> MesherOptions:
    """Render dimension-specific mesher quality controls in the sidebar."""
    st.subheader("Mesher quality")
    triangle_min_angle = defaults.triangle_min_angle
    tetgen_quality_ratio = defaults.tetgen_quality_ratio
    tetgen_min_dihedral = defaults.tetgen_min_dihedral
    tetgen_max_volume = defaults.tetgen_max_volume
    bottom_margin = defaults.bottom_margin
    seam_protection_rings = defaults.seam_protection_rings

    if dimension == 2:
        triangle_min_angle = st.slider(
            "Triangle minimum angle",
            min_value=0,
            max_value=33,
            value=int(defaults.triangle_min_angle),
            step=1,
            help=(
                "Minimum angle requested for 2D triangles. Higher values avoid "
                "skinny elements but insert more points and increase mesh size. "
                "Triangle guarantees termination only up to about 28.6 degrees."
            ),
        )
    else:
        tetgen_quality_ratio = st.slider(
            "TetGen radius-edge ratio",
            min_value=1.1,
            max_value=2.5,
            value=defaults.tetgen_quality_ratio,
            step=0.1,
            help=(
                "Maximum tetrahedron radius-edge ratio. Lower values enforce "
                "better-shaped tetrahedra but add Steiner points, increase run "
                "time, and can fail on pinch-off geometry."
            ),
        )
        tetgen_min_dihedral = st.slider(
            "TetGen minimum dihedral angle",
            min_value=0.0,
            max_value=18.0,
            value=defaults.tetgen_min_dihedral,
            step=1.0,
            help=(
                "Minimum requested tetrahedron dihedral angle in degrees. Higher "
                "values suppress slivers but create more tetrahedra and make "
                "difficult geometries less likely to mesh."
            ),
        )
        volume_options = _tetgen_volume_slider_options(input_paths)
        default_volume = (
            0.0
            if defaults.tetgen_max_volume is None
            else min(
                volume_options[1:],
                key=lambda value: abs(value - defaults.tetgen_max_volume),
            )
        )
        max_volume_value = st.select_slider(
            "Maximum tetrahedron volume",
            options=volume_options,
            value=default_volume,
            format_func=_format_volume_slider_value,
            help=(
                "Global TetGen volume bound in model units cubed, on a logarithmic "
                "scale from 10^-6 to 10^-1 of this geometry's bounding-box volume. "
                "That spans roughly one million to ten ideal tetrahedra before "
                "boundary and quality refinement. Smaller values produce denser "
                "meshes; No limit leaves density to the quality constraints."
            ),
        )
        tetgen_max_volume = float(max_volume_value) or None
        bottom_margin = st.slider(
            "Bottom substrate margin",
            min_value=0.01,
            max_value=2.0,
            value=defaults.bottom_margin,
            step=0.01,
            format="%.2f",
            help=(
                "Depth added below the lowest surface, as a fraction of the "
                "geometry height. The slider spans 1% (below which region points "
                "become numerically fragile) to 200%, with 0.10 adding a 10% "
                "substrate slab."
            ),
        )
        customize_seam_protection = st.toggle(
            "Customize seam protection rings",
            value=False,
            help=(
                "Unlock the no-decimation distance around self-touching pinch-off "
                "seams. The default is tuned for robust tetrahedralization."
            ),
        )
        if customize_seam_protection:
            st.warning(
                "Reducing seam protection can create self-intersections and cause "
                "TetGen to fail. Increasing it preserves more surface faces.",
                icon="⚠️",
            )
            seam_protection_rings = st.slider(
                "Seam protection rings",
                min_value=0,
                max_value=20,
                value=defaults.seam_protection_rings,
                step=1,
                help=(
                    "Number of vertex rings around a pinch-off seam excluded from "
                    "decimation. Lower gives smaller meshes with more intersection "
                    "risk; higher is safer but preserves more triangles. Twenty "
                    "rings already protects a wide neighborhood on typical grids."
                ),
            )

    return MesherOptions(
        triangle_min_angle=float(triangle_min_angle),
        tetgen_quality_ratio=float(tetgen_quality_ratio),
        tetgen_min_dihedral=float(tetgen_min_dihedral),
        tetgen_max_volume=tetgen_max_volume,
        bottom_margin=float(bottom_margin),
        seam_protection_rings=int(seam_protection_rings),
    )


def _decimation_sidebar_controls(defaults: DecimationOptions3D) -> DecimationOptions3D:
    """Render 3D decimation controls in the sidebar and return the options."""
    st.subheader("3D decimation")
    enabled = st.toggle(
        "Decimate surfaces",
        value=defaults.enabled,
        key="decimate_surfaces",
        help=(
            "Simplify the extracted surfaces (quadric edge collapse) before "
            "TetGen runs. **On:** far fewer triangles, so tetrahedralization "
            "and rendering are much faster and the volume mesh is smaller — "
            "at the cost of smoothing out geometric detail finer than the "
            "target resolution. **Off:** the surfaces keep their full "
            "level-set resolution — most faithful geometry, but the largest "
            "and slowest meshes. Safety rails in both cases: material "
            "junction curves and domain-wall traces are always preserved "
            "exactly so layers keep conforming, and faces near self-touching "
            "pinch-off seams are never decimated."
        ),
    )
    if not enabled:
        return DecimationOptions3D(enabled=False)

    target_mode = st.radio(
        "Decimation target",
        ("Total face budget", "Target edge length"),
        horizontal=True,
        help=(
            "The total budget is distributed across the unique conforming patch "
            "complex by physical surface area. Edge length instead specifies an "
            "approximate spatial resolution in model units."
        ),
    )
    target_total_faces: int | None = None
    target_edge_length: float | None = None
    if target_mode == "Total face budget":
        face_budgets = (
            1_000,
            2_000,
            4_000,
            5_600,
            8_000,
            12_000,
            20_000,
            50_000,
            100_000,
        )
        default_budget = defaults.target_total_faces or DEFAULT_TARGET_TOTAL_FACES
        target_total_faces = st.select_slider(
            "Target total surface faces",
            options=face_budgets,
            value=min(face_budgets, key=lambda value: abs(value - default_budget)),
            help=(
                "Requested faces across unique decimatable patches. Each patch "
                "receives a share proportional to its true 3D area. Protected "
                "seams, fixed boundaries, and safety retries can make the achieved "
                "count higher."
            ),
        )
    else:
        target_edge_length = float(
            st.number_input(
                "Target triangle edge length",
                min_value=1e-6,
                value=float(defaults.target_edge_length or 0.25),
                format="%.6g",
                help=(
                    "Approximate edge length in model units. Patch targets are "
                    "derived from the area of equilateral triangles of this size."
                ),
            )
        )
    quality_threshold = st.slider(
        "Quality threshold",
        min_value=0.1,
        max_value=1.0,
        value=float(min(max(defaults.quality_threshold, 0.1), 1.0)),
        step=0.05,
        help=(
            "How strongly the collapse cost penalizes badly shaped triangles "
            "(1 ≈ demand near-equilateral, 0.1 ≈ tolerate slivers). This "
            "trades triangle shape against how far collapse can proceed, but "
            "it is *not* a simplification throttle: on flat regions any value "
            "from 0.1 to 1.0 reaches the same face count. **Higher:** "
            "well-shaped triangles that give TetGen better tetrahedra. "
            "**Lower:** tolerates skinnier triangles. Note: a value of 0 "
            "removes the shape term entirely and paradoxically stalls "
            "simplification on flat, zero-error regions — so the slider "
            "starts at 0.1."
        ),
    )
    preserve_boundary = st.toggle(
        "Preserve patch boundaries",
        value=defaults.preserve_boundary,
        help=(
            "Keep the patch boundary curves — material junction curves and "
            "the traces where surfaces meet the domain walls — exactly "
            "fixed during decimation. **On (recommended):** decimated "
            "layers keep conforming exactly where they meet, which the "
            "rest of the pipeline depends on. **Off:** ⚠️ boundaries may "
            "move or lose vertices, so adjacent layers stop matching "
            "triangle-for-triangle. Expect holes at material interfaces, "
            "“Cannot close 3D surface” errors when boundary points drift "
            "off the domain walls, wrong material region assignments, and "
            "TetGen failures. Only consider disabling for single-surface "
            "experiments where maximum simplification matters more than a "
            "valid volume mesh."
        ),
    )
    boundary_weight = defaults.boundary_weight
    if not preserve_boundary:
        st.warning(
            "Patch boundaries are free to move: layers may stop conforming, "
            "causing holes at material interfaces, “Cannot close 3D "
            "surface” errors, or TetGen failures.",
            icon="⚠️",
        )
        boundary_weight_options = (
            0.1,
            0.5,
            1.0,
            5.0,
            10.0,
            50.0,
            100.0,
            500.0,
            1000.0,
        )
        boundary_weight = st.select_slider(
            "Boundary weight",
            options=boundary_weight_options,
            value=min(
                boundary_weight_options,
                key=lambda option: abs(option - defaults.boundary_weight),
            ),
            help=(
                "How important the patch boundary is while it is free to "
                "move (only used when Preserve patch boundaries is off). "
                "1 treats the boundary like any other part of the surface; "
                "the effect grows on a log scale, so the slider stops do "
                "too. **Higher:** removes fewer boundary vertices and keeps "
                "junction curves closer to their original shape — safer, "
                "but less simplification there. **Lower:** simplifies the "
                "boundary as aggressively as the interior, maximizing face "
                "reduction but distorting junctions and wall traces the "
                "most."
            ),
        )
    optimal_placement = st.toggle(
        "Optimal vertex placement",
        value=defaults.optimal_placement,
        help=(
            "Where the merged vertex lands when an edge collapses. **On:** "
            "placed at the error-minimizing position, giving a smoother, "
            "more accurate surface for the same face count — but new "
            "vertices move off the original surface, which raises the risk "
            "of self-intersections (and TetGen failures) where two sheets "
            "of the surface run close together. **Off:** vertices stay at "
            "original surface positions — slightly blockier result, but "
            "safer for narrow gaps and near-touching films."
        ),
    )
    planar_quadric = st.toggle(
        "Planar quadric",
        value=defaults.planar_quadric,
        help=(
            "In perfectly flat regions the standard quadric error is zero, "
            "so the simplifier collapses them arbitrarily — often into a "
            "few long, badly shaped triangles. This option adds a small "
            "shape-regularizing term in flat areas. **On:** flat walls and "
            "floors keep a cleaner, better-shaped triangulation (as a side "
            "effect, somewhat more triangles are preserved there), which "
            "gives TetGen better elements. **Off:** flat regions simplify "
            "as aggressively as possible — fewer faces, but sliver "
            "triangles can appear and degrade tetrahedron quality."
        ),
    )
    planar_weight_options = (0.0, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0)
    planar_weight = st.select_slider(
        "Planar weight",
        options=planar_weight_options,
        value=min(
            planar_weight_options,
            key=lambda option: abs(option - defaults.planar_weight),
        ),
        help=(
            "Strength of the flat-region regularization (only used when "
            "Planar quadric is on). The effect grows on a log scale, so "
            "the slider stops do too: 0 disables the term entirely; 1 "
            "preserves flat regions about as strongly as a real patch "
            "border. **Higher:** flat areas keep more, better-shaped "
            "triangles — better element quality, slightly more faces. "
            "**Lower:** flat areas are simplified more aggressively — "
            "fewer faces, higher sliver risk. The 0.001 default adds just "
            "enough regularization to keep flat-area triangles reasonable."
        ),
    )
    return DecimationOptions3D(
        enabled=True,
        target_total_faces=target_total_faces,
        target_edge_length=target_edge_length,
        quality_threshold=float(quality_threshold),
        preserve_boundary=preserve_boundary,
        boundary_weight=float(boundary_weight),
        optimal_placement=optimal_placement,
        planar_quadric=planar_quadric,
        planar_weight=float(planar_weight),
    )


def app() -> None:  # noqa: C901, PLR0912, PLR0915
    """Render the Streamlit application."""
    st.set_page_config(page_title="lsmesher live viewer", layout="wide")

    root = Path.cwd()
    st.session_state.setdefault("preset_paths", [])
    st.session_state.setdefault("preset_message", "")
    st.session_state.setdefault("preset_name", "")
    st.session_state.setdefault("preset_description", "")
    st.session_state.setdefault("preset_dimension", None)
    preview_modes = ["Processed mesh", "Raw selected files"]
    if st.session_state.get("preview_mode") not in preview_modes:
        st.session_state["preview_mode"] = preview_modes[0]

    selected_paths: list[Path] = []
    selected_preset: Preset | None = None
    presets = _presets(root)
    preset_dimension = st.sidebar.radio(
        "Preset dimension",
        ["2D", "3D"],
        index=1,
        horizontal=True,
    )
    expected_dimension = int(preset_dimension[0])
    presets = [preset for preset in presets if preset.dimension == expected_dimension]
    if not presets:
        st.sidebar.info("No presets found.")
    else:
        preset_by_name = {preset.name: preset for preset in presets}
        selected_preset_name = st.sidebar.selectbox(
            "Preset",
            list(preset_by_name),
        )
        selected_preset = preset_by_name[selected_preset_name]
        if selected_preset_name != st.session_state["preset_name"]:
            st.session_state["preset_paths"] = []
            st.session_state["preset_message"] = ""
            st.session_state["preset_name"] = selected_preset.name
            st.session_state["preset_description"] = selected_preset.description
            st.session_state["preset_dimension"] = selected_preset.dimension
            if selected_preset.files:
                with st.spinner(f"Loading {selected_preset.name}..."):
                    selected_paths, message = _load_preset(selected_preset, root)
                st.session_state["preset_paths"] = [
                    str(path) for path in selected_paths
                ]
                st.session_state["preset_message"] = message
            st.rerun()
    selected_paths = [Path(path) for path in st.session_state["preset_paths"]]

    if st.sidebar.button("✕ Clear active preset"):
        st.session_state["preset_paths"] = []
        st.session_state["preset_message"] = ""
        st.session_state["preset_name"] = ""
        st.session_state["preset_description"] = ""
        st.session_state["preset_dimension"] = None
        st.rerun()

    viewer_tab, config_tab = st.sidebar.tabs(["Viewer", "Config"])
    config_values: dict[str, str] = {}
    with config_tab:
        if selected_preset is not None and selected_preset.config is not None:
            st.subheader("Preset config")
            config_values = {
                entry.key: st.text_input(
                    entry.key,
                    value=entry.value,
                    key=(
                        f"preset_config_{_slug(selected_preset.name)}_"
                        f"{_slug(entry.key)}_{_slug(entry.value)}"
                    ),
                )
                for entry in _read_config_entries(selected_preset.config)
            }
            if st.button("⚙ Generate preset"):
                with st.spinner(f"Generating {selected_preset.name}..."):
                    selected_paths, message = _load_preset(
                        selected_preset,
                        root,
                        config_values=config_values,
                        force_generate=True,
                        output_dir=_preset_output_dir(root, selected_preset.name)
                        / "generated_preset",
                    )
                st.session_state["preset_paths"] = [
                    str(path) for path in selected_paths
                ]
                st.session_state["preset_message"] = message
                st.rerun()
        else:
            st.info("This preset has no editable config.")

    with viewer_tab:
        st.header("Inputs")
        epsilon_exponent = st.select_slider(
            "2D collinear epsilon exponent",
            options=tuple(range(-8, 0)),
            value=-6,
            format_func=lambda exponent: f"10^{exponent}",
            help=("Epsilon is 10 raised to this exponent, from 10^-8 through 10^-1."),
        )
        epsilon = 10.0 ** int(epsilon_exponent)
        preview_mode = st.radio(
            "Preview",
            preview_modes,
            key="preview_mode",
        )
        renderer = st.radio(
            "Renderer",
            ["PyVista PNG", "Plotly interactive"],
            help="PyVista PNG renders server-side and handles large 2D meshes better.",
        )
        processed_display = "Filled triangles"
        if preview_mode == "Processed mesh":
            processed_display = st.radio(
                "Processed mesh display",
                ["Filled triangles", "Wireframe edges"],
                help="Wireframe edges skips triangle fill and draws all cell edges, including interior triangle edges.",
            )
        max_wireframe_edges = DEFAULT_MAX_WIREFRAME_EDGES
        if processed_display == "Wireframe edges":
            max_wireframe_edges = st.slider(
                "Max wireframe edges",
                min_value=1_000,
                max_value=500_000,
                value=DEFAULT_MAX_WIREFRAME_EDGES,
                step=1_000,
                help="Higher values show more edges but can make Plotly/Streamlit slow on large meshes.",
            )
        run_mesher = st.toggle(
            "Run mesher",
            value=True,
            help="Runs Triangle for 2D presets and TetGen for 3D presets.",
        )
        dimension = st.session_state["preset_dimension"] or expected_dimension
        output_format = "vtu" if dimension == 2 or run_mesher else "vtp"
        mesher = _mesher_quality_sidebar_controls(
            dimension, MesherOptions(), selected_paths
        )
        decimation = DecimationOptions3D()
        if dimension == 3:
            decimation = _decimation_sidebar_controls(DecimationOptions3D())
        st.button("↻ Recompute outputs")
        show_edges = st.toggle("Show edges", value=True)
        color = st.color_picker("Mesh color", "#8dd3ff")
    if not selected_paths:
        st.info("Generate or select a preset.")
        return

    title = st.session_state["preset_name"] or selected_paths[0].stem
    st.subheader(title)
    output_dir = _preset_output_dir(root, title)
    st.caption(f"Generated files: `{output_dir}`")

    try:
        if preview_mode == "Raw selected files":
            for path in selected_paths:
                if renderer == "PyVista PNG":
                    _render_mesh_png(
                        path,
                        options=PyVistaPngOptions(
                            show_edges=show_edges,
                            color=color,
                        ),
                    )
                else:
                    _render_mesh(
                        path,
                        options=MeshRenderOptions(show_edges=show_edges, color=color),
                    )
        elif preview_mode == "Pipeline polygon":
            output_path = _write_2d_polygon_preview_output(
                selected_paths,
                epsilon=epsilon,
                output_dir=output_dir / "pipeline_polygon",
            )
            if renderer == "PyVista PNG":
                _render_mesh_png(
                    output_path,
                    options=PyVistaPngOptions(show_edges=True, color=color),
                )
            else:
                _render_mesh(
                    output_path,
                    options=MeshRenderOptions(show_edges=show_edges, color=color),
                )
        else:
            processed_options = ProcessedMeshOptions(
                epsilon=epsilon,
                output_format=output_format,
                run_mesher=run_mesher,
                decimation=decimation,
                mesher=mesher,
            )
            output_path: Path | None = None
            attempts = _processed_mesh_retry_options(selected_paths, processed_options)
            for attempt_index, (label, attempt_options, retry_reason) in enumerate(
                attempts,
                start=1,
            ):
                if retry_reason is not None:
                    st.warning(
                        f"Retrying processed mesh with {label}: {retry_reason}",
                    )
                try:
                    output_path = _write_processed_mesh_output(
                        selected_paths,
                        options=attempt_options,
                        output_dir=output_dir / "processed_mesh",
                    )
                    if attempt_index > 1:
                        st.success(f"Retry succeeded with {label}.")
                    break
                except Exception as exc:
                    if attempt_index < len(attempts):
                        st.warning(
                            f"Processed mesh attempt {attempt_index} failed with "
                            f"{label}: {_exception_summary(exc)}"
                        )
                    else:
                        st.error(_processed_mesh_failure_guidance(processed_options))
                        raise
            output_path = cast("Path", output_path)
            wireframe = processed_display == "Wireframe edges"
            if renderer == "PyVista PNG":
                _render_mesh_png(
                    output_path,
                    options=PyVistaPngOptions(
                        show_edges=show_edges or wireframe,
                        color=color,
                        fill_surfaces=not wireframe,
                        all_cell_edges=wireframe,
                    ),
                )
            else:
                _render_mesh(
                    output_path,
                    options=MeshRenderOptions(
                        show_edges=show_edges or wireframe,
                        color=color,
                        fill_surfaces=not wireframe,
                        all_cell_edges=wireframe,
                        max_edges=max_wireframe_edges if wireframe else None,
                    ),
                )
            _show_tetgen_log(output_path)
            _show_decimation_report(output_path)
            if selected_preset is not None:
                _show_preset_data_download(
                    selected_preset,
                    root,
                    output_path=output_path,
                    raw_files=selected_paths,
                    config_values=config_values,
                )
    except Exception as exc:  # noqa: BLE001 - Streamlit should display pipeline errors.
        st.exception(exc)


def main() -> None:
    """Launch the Streamlit viewer from the console script."""
    os.environ.setdefault("PYVISTA_OFF_SCREEN", "true")
    viewer_path = Path(__file__).resolve()
    sys.argv = ["streamlit", "run", str(viewer_path), *sys.argv[1:]]

    streamlit_main()


if __name__ == "__main__":
    app()
